services:
  api:
    image: fastapi-cloudrun:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.app
    environment:
      - PORT=8080
    restart: unless-stopped
    container_name: fastapi-api


